## Services
google_analytics:
duoshuo:

## Meta
favicon: /avatars/v1.ico
icon: /avatars/v1.ico
source_url: 'https://github.com/senlypan/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于大晚': /about
  '简历': /resume
  '在读书单': /booklist
  '所有日志': /list
  
right_menus:
  '超级大脑':
    target: '_blank'
    href: 'http://super.panshenlian.com'
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/senlypan/blog'


## Banners && Widgets
banners:
  jade: |
    | 大晚最近在思考如何 #[a(href='https://hexo.io/') 搭建] 一套个人网站，持续摸索中。

widgets:
  -
    markdown: |
      我是大晚，真名潘深练，生于 1990 年，英文 ID 是 biglate.

      * 创业Loser
      * 完美主义者

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '412560226'
  mobile: '13276907188'
  github: 'senlypan'

