## Services
google_analytics: 'G-XWB09PF43E'
giscus: 1
share_card: 1
biglate_analytics: 1
biglate_ajax: 1

## Meta
rss: /atom.xml
favicon: /avatars/v1.ico
icon: /avatars/v1.ico
source_url: 'https://github.com/senlypan/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于我': /about
  '简历': /resume
  '在读书单': /booklist
  '在听播客': /podcasts
  '技术日志': /list
  '生活掠影': /live
  '日常叨叨叨': /happened
  '订阅我': /feed
  
right_menus:
  '科技周刊': /weekly
  '访问统计': /visit
  'Github':
    target: '_blank'
    href: 'https://github.com/senlypan/blog'


## Banners && Widgets 
banners:
  jade: |
    | 2025-01-14：
    | 职业、家庭、认知之拐点，或成人生关键之转折。

widgets:
  -
    markdown: |
      Hi, 我是潘深练，一名大龄程序员，坚定不移热爱技术，平时喜欢捣鼓一些小创意，有很多理想，也有点理想主义，同时也是一名读瘾晚期患者。

      ❤️做了一款阅读工具叫 [竹白百科](https://www.zhubai.wiki/)

  -
    markdown: |
      <img src="https://www.panshenlian.com/images/post/wechat/v3.jpg" alt="第一次当爸爸吖" width="100%"> 
      Weibo: <a href="https://weibo.com/senlypan" target="_blank">划水弹夹想吃肉</a><br/>
      Bilibili: <a href="https://space.bilibili.com/232947570" target="_blank">第一次当爸爸吖</a><br/> 
      Twitter: <a href="https://twitter.com/man_paddle" target="_blank">划水怪</a><br/> 
      Email: panshenlian#gmail.com 

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: ''
  mobile: ''
  github: 'senlypan'

