## Services
google_analytics: 'G-XWB09PF43E'
giscus: 1

## Meta
rss: http://panshenlian/atom.xml
favicon: /avatars/v1.ico
icon: /avatars/v1.ico
source_url: 'https://github.com/senlypan/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于大晚': /about
  '简历': /resume
  '在读书单': /booklist
  '在听播客': /podcasts
  '技术日志': /list
  '生活掠影': /live
  '日常叨叨叨': /happened
  '订阅我': /feed
  
right_menus:
  '科技周刊': /weekly
  '产品半月刊': /product
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/senlypan/blog'


## Banners && Widgets
banners:
  jade: |
    | 2022-05-01：二〇二二年四月，匆匆终结，极为丰满，从一号准备孩子的四岁生日会开始，就隐约有种忙碌预感，直到刚刚在公园被疫情防控安保人员撵走，我们一家三口拖着帐篷、书籍、电脑、零食、玩具，顶着三个 26°C 的太阳，走进一家丹尼斯七天地星巴克，坐下，咖啡厅舒缓的音乐，让神经很快松弛，缓过神，想想今天既狼狈又好笑，趁着孩子酣睡，打开电脑，回忆 #[a(href='https://www.panshenlian.com/2022/05/01/live-004-april-day-in-2022/',target='_blank') 四月]。
widgets:
  -
    markdown: |
      <img src="http://www.panshenlian.com/images/post/me/me-in-2019.jpg" alt="大晚" width="100%"> 
      Hi，我是大晚，真名潘深练，英文ID：biglate ，未来想做自由职业者，相信技术，会让生活更有趣。

      * [《 无聊科技正经事周刊》](https://weekly.panshenlian.com) 
      * [《 潘深练的QA手册 》](http://qa.panshenlian.com/) 
      * [《 Java并发编程学习文档 》](http://concurrent-programming.panshenlian.com/#/zh-cn/)
      * [《 Java虚拟机学习手册 》](http://jvm.panshenlian.com/#/)
      * [《 Spring框架学习手册 》](http://spring.panshenlian.com/) 

  -
    markdown: |
      <img src="http://www.panshenlian.com/images/post/wechat/v2.jpg" alt="潘潘和他的朋友们" width="100%"> 
      Weibo: <a href="https://weibo.com/senlypan" target="_blank">划水弹夹想吃肉</a><br/>
      Twitter: <a href="https://twitter.com/man_paddle" target="_blank">划水怪</a><br/> 
      Email: panshenlian@gmail.com 

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '412560226'
  mobile: '13276907188'
  github: 'senlypan'

