## Services
google_analytics: 'G-XWB09PF43E'
duoshuo:

## Meta
rss: http://panshenlian/atom.xml
favicon: /avatars/v1.ico
icon: /avatars/v1.ico
source_url: 'https://github.com/senlypan/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于大晚': /about
  '简历': /resume
  '在读书单': /booklist
  '在听播客': /podcasts
  '所有日志': /list
  '生活掠影': /live
  '订阅我': /feed
  
right_menus:
  '科技周刊': /weekly
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/senlypan/blog'


## Banners && Widgets
banners:
  jade: |
    | 大晚最近在梳理分布式系统设计相关实践，还有一本在读的书 #[a(href='https://book.douban.com/subject/2240482/') 《走在人生边上》] ，#[a(href='https://book.douban.com/author/4503676/') 杨绛先生] 在书里以问答的形式说了很多神鬼、人本性、天命的内容，又强调了人生实苦，每个人都需要修身、锻炼灵魂，实现人生价值，文字很亲近，内容值得思考。

widgets:
  -
    markdown: |
      Hi，我是大晚，真名潘深练，英文ID：biglate ，未来想做自由职业者，相信技术，会让生活更有趣。

      * [《 无聊科技正经事周刊》](http://weekly.panshenlian.com/) 
      * [《 潘深练的QA手册 》](http://qa.panshenlian.com/) 
      * [《 Java并发编程学习文档 》](http://concurrent-programming.panshenlian.com/#/zh-cn/)
      * [《 Java虚拟机学习手册 》](http://jvm.panshenlian.com/#/)
      * [《 Spring框架学习手册 》](http://spring.panshenlian.com/) 

  -
    markdown: |
      <img src="http://www.panshenlian.com/images/post/wechat/v1.jpg" alt="潘潘和他的朋友们" width="100%"> 
      Weibo: <a href="https://weibo.com/senlypan" target="_blank">划水弹夹想吃肉</a><br/>
      Email: panshenlian@gmail.com 

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '412560226'
  mobile: '13276907188'
  github: 'senlypan'

