## Services
google_analytics: 'G-XWB09PF43E'
giscus: 1
share_card: 1
biglate_analytics: 1
biglate_ajax: 1

## Meta
rss: http://panshenlian/atom.xml
favicon: /avatars/v1.ico
icon: /avatars/v1.ico
source_url: 'https://github.com/senlypan/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于大晚': /about
  '简历': /resume
  '在读书单': /booklist
  '在听播客': /podcasts
  '技术日志': /list
  '生活掠影': /live
  '日常叨叨叨': /happened
  '订阅我': /feed
  
right_menus:
  '科技周刊': /weekly
##  '产品季刊': /product
  '访问统计': /visit
  '开往': 
    target: '_blank'
    href: 'https://travellings.link'
  'Github':
    target: '_blank'
    href: 'https://github.com/senlypan/blog'


## Banners && Widgets 
banners:
  jade: |
    | 2022-10-13：有时候做决定确实拧巴纠结，今天看到一段话，挺有启发，可供参考：“如果你遇到一堵墙，基于畏惧心理，纠结要不要爬的时候，就先把帽子丢过去；这样的话，接下来就根本不是犹豫要不要爬过去，而是怎么爬过去的问题。”。

widgets:
  -
    markdown: |
      Hi，我是大晚，真名潘深练，英文ID：biglate ，未来想做自由职业者，相信技术，会让生活更有趣。

      * [《 无聊科技正经事周刊》](https://weekly.panshenlian.com) 
      * [《 Java并发编程学习小册 》](http://concurrent-programming.panshenlian.com/#/zh-cn/)
      * [《 架构师演进小册 》](http://qa.panshenlian.com/#/)

  -
    markdown: |
      <img src="https://www.panshenlian.com/images/post/wechat/v2.jpg" alt="潘潘和他的朋友们" width="100%"> 
      Weibo: <a href="https://weibo.com/senlypan" target="_blank">划水弹夹想吃肉</a><br/>
      Twitter: <a href="https://twitter.com/man_paddle" target="_blank">划水怪</a><br/> 
      Email: panshenlian#gmail.com 

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: ''
  mobile: ''
  github: 'senlypan'

